THEME = {
    "primary":        "#4F86F7",
    "primary_dark":   "#3a6bc0",
    "bg_main":        "#F4F6F9",
    "bg_card":        "#FFFFFF",
    "sidebar":        "#1E2A3A",
    "sidebar_text":   "#FFFFFF",
    "sidebar_sub":    "#8A9BB0",
    "sidebar_hover":  "#2A3A4E",
    "sidebar_active": "#2E5BFF",
    "text_main":      "#333333",
    "text_sub":       "#888888",
    "border":         "#E0E0E0",
    "success":        "#28A745",
    "danger":         "#FF4D4D",
    "warning":        "#FFC107",
}